jobui and jobdeck now working to successfully submit the prompt, wait nicely for completion and then put the raw generated image data into the completion div. VERY CLOSE. next pushes will actually show the image. in this push is also more work trying to get a stable diffusion build to work and that effort failed after a lot of struggle with python dependency conflicts.

diff --git a/stabled/Dockerfile b/stabled/Dockerfile
--- a/stabled/Dockerfile
+++ b/stabled/Dockerfile
@@ -1,52 +1,149 @@
+# ---------------------------------------------------------------------------- #
+#                         Stage 1: Download the models                         #
+# ---------------------------------------------------------------------------- #
+FROM alpine/git:2.36.2 as download
 
-# Use the Python 3.10.9-slim image as the base
-FROM python:3.10.9-slim
+COPY builder/clone.sh /clone.sh
 
-RUN mkdir -p /app/models
+# Clone the repos and clean unnecessary files
+RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6 && \
+    rm -rf data assets **/*.ipynb
 
-WORKDIR /app
+RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git 47b6b607fdd31875c9279cd2f4f16b92e4ea958e && \
+    rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif
 
-# Copy the Stable Diffusion model into the container
-# (Assuming you have the model files on your local machine)
-# This is done early so it has a lower chance of having layers invalidated during build, saving long up/download times.
-COPY ./builder/models/* /app/models/
+RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af && \
+    rm -rf assets inputs
 
+RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9 && \
+    . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git 5b3af030dd83e0297272d861c19477735d0317ec && \
+    . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2486589f24165c8e3b303f84e9dbbea318df83e8 && \
+    . /clone.sh generative-models https://github.com/Stability-AI/generative-models 45c443b316737a4ab6e40413d7794a7f5657c19f
 
-# Install system dependencies required by Stable Diffusion and the API
-RUN apt-get update && apt-get install -y \
-    git \
-    libglib2.0-0 \
-    libsm6 \
-    libxext6 \
-    libxrender-dev \
-    curl \
-    && apt-get clean
-
-
-# Install Python dependencies for Stable Diffusion and the API
-RUN pip install --upgrade pip
-RUN pip install --upgrade setuptools
-
-# Copy the requirements.txt file into the container
-COPY ./builder/requirements.txt /app/requirements.txt
-
-RUN pip install --no-cache-dir -r /app/requirements.txt
-# RUN pip install torch torchvision torchaudio transformers diffusers flask  # Prior to requirements.txt
-
-# Install diffusers with PyTorch support - Keeping this separate for now. The reqs file includes "diffusers".
-# RUN #pip install "diffusers[torch]"  # This is now install in the reqs file, right after "diffusers" (we do both)
-
-RUN pip install transformers
-RUN pip install diffusers
-RUN pip install diffusers[torch]
+RUN apk add --no-cache wget && \
+    wget -q -O /model.safetensors https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.safetensors
 
 
-# Expose the API port
-EXPOSE 5000
+# ---------------------------------------------------------------------------- #
+#                        Stage 3: Build the final image                        #
+# ---------------------------------------------------------------------------- #
+FROM python:3.10.9-slim as build_final_image
 
-# Copy the API script into the container
-COPY ./src/app.py /app/app.py
+ARG SHA=5ef669de080814067961f28357256e8fe27544f4
 
-# Set the entrypoint to run the API when the container starts
-CMD ["python", "app.py"]
+ENV DEBIAN_FRONTEND=noninteractive \
+    PIP_PREFER_BINARY=1 \
+    LD_PRELOAD=libtcmalloc.so \
+    ROOT=/stable-diffusion-webui \
+    PYTHONUNBUFFERED=1
 
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+RUN export COMMANDLINE_ARGS="--skip-torch-cuda-test --precision full --no-half"
+RUN export TORCH_COMMAND='pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/rocm5.6'
+
+RUN apt-get update && \
+    apt install -y \
+    fonts-dejavu-core rsync git jq moreutils aria2 wget libgoogle-perftools-dev procps libgl1 libglib2.0-0 && \
+    apt-get autoremove -y && rm -rf /var/lib/apt/lists/* && apt-get clean -y
+
+RUN --mount=type=cache,target=/cache --mount=type=cache,target=/root/.cache/pip \
+    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
+
+RUN --mount=type=cache,target=/root/.cache/pip \
+    git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git && \
+    cd stable-diffusion-webui && \
+    git reset --hard ${SHA}
+#&& \ pip install -r requirements_versions.txt
+
+COPY --from=download /repositories/ ${ROOT}/repositories/
+COPY --from=download /model.safetensors /model.safetensors
+RUN mkdir ${ROOT}/interrogate && cp ${ROOT}/repositories/clip-interrogator/data/* ${ROOT}/interrogate
+RUN --mount=type=cache,target=/root/.cache/pip \
+    pip install -r ${ROOT}/repositories/CodeFormer/requirements.txt
+
+
+# Install Python dependencies (Worker Template)
+COPY builder/requirements.txt /requirements.txt
+
+#RUN --mount=type=cache,target=/root/.cache/pip \
+#    pip install --upgrade pip && \
+#    pip install --upgrade -r /requirements.txt --no-cache-dir && \
+#    rm /requirements.txt
+
+RUN #--mount=type=cache,target=/root/.cache/pip pip install --upgrade pip
+RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip==24.0
+
+RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade -r /requirements.txt --no-cache-dir
+
+RUN rm /requirements.txt
+
+
+ADD src .
+
+COPY builder/cache.py /stable-diffusion-webui/cache.py
+RUN cd /stable-diffusion-webui && python cache.py --use-cpu=all --ckpt /model.safetensors
+
+# Cleanup section (Worker Template)
+RUN apt-get autoremove -y && \
+    apt-get clean -y && \
+    rm -rf /var/lib/apt/lists/*
+
+# Set permissions and specify the command to run
+RUN chmod +x /start.sh
+CMD /start.sh
+
+
+#########################################################################
+#
+## Use the Python 3.10.9-slim image as the base
+#FROM python:3.10.9-slim
+#
+#RUN mkdir -p /app/models
+#
+#WORKDIR /app
+#
+## Copy the Stable Diffusion model into the container
+## (Assuming you have the model files on your local machine)
+## This is done early so it has a lower chance of having layers invalidated during build, saving long up/download times.
+#COPY ./builder/models/* /app/models/
+#
+#
+## Install system dependencies required by Stable Diffusion and the API
+#RUN apt-get update && apt-get install -y \
+#    git \
+#    libglib2.0-0 \
+#    libsm6 \
+#    libxext6 \
+#    libxrender-dev \
+#    curl \
+#    && apt-get clean
+#
+#
+## Install Python dependencies for Stable Diffusion and the API
+#RUN pip install --upgrade pip
+#RUN pip install --upgrade setuptools
+#
+## Copy the requirements.txt file into the container
+#COPY ./builder/requirements.txt /app/requirements.txt
+#
+#RUN pip install --no-cache-dir -r /app/requirements.txt
+## RUN pip install torch torchvision torchaudio transformers diffusers flask  # Prior to requirements.txt
+#
+## Install diffusers with PyTorch support - Keeping this separate for now. The reqs file includes "diffusers".
+## RUN #pip install "diffusers[torch]"  # This is now install in the reqs file, right after "diffusers" (we do both)
+#
+#RUN pip install transformers
+#RUN pip install diffusers
+#RUN pip install diffusers[torch]
+#
+#
+## Expose the API port
+#EXPOSE 5000
+#
+## Copy the API script into the container
+#COPY ./src/app.py /app/app.py
+#
+## Set the entrypoint to run the API when the container starts
+#CMD ["python", "app.py"]
+#
